CREATE OR REPLACE TABLE associations_clean AS
SELECT DISTINCT
  "SNPS" AS rsid,
  SPLIT_PART("STRONGEST SNP-RISK ALLELE", '-', 2) AS risk_allele,
  TRY_CAST("P-VALUE" AS DOUBLE) AS pvalue,
  TRY_CAST("OR or BETA" AS DOUBLE) AS beta,
  "MAPPED_TRAIT" AS trait,
  "MAPPED_TRAIT_URI" AS trait_uri,
  "STUDY ACCESSION" AS study_id
FROM read_csv_auto('associations.tsv', delim='\t', header=true)
WHERE
  "SNPS" IS NOT NULL AND
  TRY_CAST("P-VALUE" AS DOUBLE) IS NOT NULL AND
  TRY_CAST("OR or BETA" AS DOUBLE) IS NOT NULL AND
  "STRONGEST SNP-RISK ALLELE" LIKE 'rs%-%' AND
  "MAPPED_TRAIT" IS NOT NULL AND
  "MAPPED_TRAIT_URI" IS NOT NULL;
