// Mocks generated by Mockito 5.4.6 from annotations
// in vibe_health/test/features/vibes/controllers/vibe_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vibe_health/features/vibes/domain/vibe.dart' as _i2;
import 'package:vibe_health/features/vibes/domain/vibe_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVibe_0 extends _i1.SmartFake implements _i2.Vibe {
  _FakeVibe_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VibeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVibeRepository extends _i1.Mock implements _i3.VibeRepository {
  MockVibeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createVibe(_i2.Vibe? vibe) =>
      (super.noSuchMethod(
            Invocation.method(#createVibe, [vibe]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Vibe>> listVibes({
    required DateTime? from,
    required DateTime? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listVibes, [], {#from: from, #to: to}),
            returnValue: _i4.Future<List<_i2.Vibe>>.value(<_i2.Vibe>[]),
          )
          as _i4.Future<List<_i2.Vibe>>);

  @override
  _i4.Future<_i2.Vibe> getVibeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVibeById, [id]),
            returnValue: _i4.Future<_i2.Vibe>.value(
              _FakeVibe_0(this, Invocation.method(#getVibeById, [id])),
            ),
          )
          as _i4.Future<_i2.Vibe>);

  @override
  _i4.Future<void> updateVibe(_i2.Vibe? vibe) =>
      (super.noSuchMethod(
            Invocation.method(#updateVibe, [vibe]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteVibe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVibe, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
