// Mocks generated by Mockito 5.4.6 from annotations
// in vibe_health/test/data/vibes/repositories/http_vibe_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vibe_health/data/vibes/api/vibe_api.dart' as _i3;
import 'package:vibe_health/data/vibes/dto/vibe_dto.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVibeDto_0 extends _i1.SmartFake implements _i2.VibeDto {
  _FakeVibeDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VibeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockVibeApi extends _i1.Mock implements _i3.VibeApi {
  MockVibeApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.VibeDto> createVibe(_i2.VibeDto? vibe) =>
      (super.noSuchMethod(
            Invocation.method(#createVibe, [vibe]),
            returnValue: _i4.Future<_i2.VibeDto>.value(
              _FakeVibeDto_0(this, Invocation.method(#createVibe, [vibe])),
            ),
          )
          as _i4.Future<_i2.VibeDto>);

  @override
  _i4.Future<List<_i2.VibeDto>> listVibes({
    required DateTime? from,
    required DateTime? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listVibes, [], {#from: from, #to: to}),
            returnValue: _i4.Future<List<_i2.VibeDto>>.value(<_i2.VibeDto>[]),
          )
          as _i4.Future<List<_i2.VibeDto>>);

  @override
  _i4.Future<_i2.VibeDto> getVibeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVibeById, [id]),
            returnValue: _i4.Future<_i2.VibeDto>.value(
              _FakeVibeDto_0(this, Invocation.method(#getVibeById, [id])),
            ),
          )
          as _i4.Future<_i2.VibeDto>);

  @override
  _i4.Future<_i2.VibeDto> updateVibe(String? id, _i2.VibeDto? vibe) =>
      (super.noSuchMethod(
            Invocation.method(#updateVibe, [id, vibe]),
            returnValue: _i4.Future<_i2.VibeDto>.value(
              _FakeVibeDto_0(this, Invocation.method(#updateVibe, [id, vibe])),
            ),
          )
          as _i4.Future<_i2.VibeDto>);

  @override
  _i4.Future<void> deleteVibe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVibe, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
